name: cp
description: CP convert to Flutter

publish_to: "none"

version: 1.2.17+120001

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_shimmer: ^1.0.0
  connectivity_plus: ^2.3.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_time_picker_spinner: ^2.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  hive: ^2.0.5
  intl: ^0.17.0
  json_annotation: ^4.5.0
  mask_text_input_formatter: ^2.3.0
  multiselect: ^0.0.7
  path_provider: ^2.0.10
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  change_app_package_name: ^1.1.0
  easy_debounce: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_serializable: ^6.2.0

flutter_native_splash:
  image: assets/images/login/splash.png
  color: "#32333D"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/login/launcher.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/images/home/
    - assets/images/home/scene/
    - assets/images/account/
    - assets/images/message/
